# Generated by Django 2.2.3 on 2020-05-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('home', 'Home & Bills'), ('transport', 'Transport'), ('essentials', 'Essentials'), ('clothes', 'Clothes & Shoes'), ('health', 'Health & Beauty'), ('education', 'Education'), ('fun', 'Entertainment & Travel'), ('cash', 'Cash')], default='cash', max_length=30)),
            ],
        ),
    ]
